export const REQUEST_NEW_ARTICLE = 'article/REQUEST_NEW_ARTICLE';
export const REQUEST_NEW_ARTICLE_COMPLETED = 'article/REQUEST_NEW_ARTICLE_COMPLETED';
export const REQUEST_NEW_ARTICLE_FAILED = 'article/REQUEST_NEW_ARTICLE_FAILED';

export const REQUEST_CHANGE_ARTICLE = 'article/REQUEST_CHANGE_ARTICLE';
export const REQUEST_CHANGE_ARTICLE_COMPLETED = 'article/REQUEST_CHANGE_ARTICLE_COMPLETED';
export const REQUEST_CHANGE_ARTICLE_FAILED = 'article/REQUEST_CHANGE_ARTICLE_FAILED';

export const REQUEST_DELETE = 'article/REQUEST_DELETE_ARTICLE';
export const REQUEST_DELETE_COMPLETED = 'article/REQUEST_DELETE_ARTICLE_COMPLETED';
export const REQUEST_DELETE_FAILED = 'article/REQUEST_DELETE_ARTICLE_FAILED';

export const REQUEST_SEARCH = 'article/REQUEST_SEARCH';
export const REQUEST_SEARCH_COMPLETED = 'article/REQUEST_SEARCH_COMPLETED';
export const REQUEST_SEARCH_FAILED = 'article/REQUEST_SEARCH_FAILED';

export const REQUEST_SEARCH_BY_TITLE_AND_AUTHOR = 'article/REQUEST_SEARCH_BY_TITLE_AND_AUTHOR';
export const REQUEST_SEARCH_BY_TITLE_AND_AUTHOR_COMPLETED = 'article/REQUEST_SEARCH_BY_TITLE_AND_AUTHOR_COMPLETED';
export const REQUEST_SEARCH_BY_TITLE_AND_AUTHOR_FAILED = 'article/REQUEST_SEARCH_BY_TITLE_AND_AUTHOR_FAILED';

export const NEW_ARTICLE_SHOWN = 'article/NEW_ARTICLE_SHOWN';
export const CALL_REFETCHING_ARTICLES = 'article/CALL_REFETCHING_ARTICLES ';
export const CALL_REFETCHING_ARTICLES_COMPLETED = 'article/CALL_REFETCHING_ARTICLES_COMPLETED';
